# Generated by Django 4.1.7 on 2023-07-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAutor', models.CharField(max_length=100)),
                ('activoAutor', models.BooleanField(default=True)),
                ('actualizaAutor', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=100)),
                ('activoCategoria', models.BooleanField(default=True)),
                ('actualizaCategoria', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('idEditorial', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEditorial', models.CharField(max_length=100)),
                ('activoEditorial', models.BooleanField(default=True)),
                ('actualizaEditorial', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('idLector', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLector', models.CharField(max_length=100)),
                ('direccionLector', models.CharField(max_length=100)),
                ('telefonoLector', models.CharField(max_length=50)),
                ('correoLector', models.CharField(max_length=50)),
                ('documentoLector', models.CharField(max_length=50)),
                ('activoLector', models.BooleanField(default=True)),
                ('actualizaLector', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('estadoPrestamo', models.CharField(choices=[('1', 'Libre'), ('2', 'Prestado')], default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('direccionUsuario', models.CharField(max_length=100)),
                ('telefonoUsuario', models.CharField(max_length=50)),
                ('correoUsuario', models.CharField(max_length=50)),
                ('documentoUsuario', models.CharField(max_length=50)),
                ('activoUsuario', models.BooleanField(default=True)),
                ('actualizaUsuario', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('tituloLibro', models.CharField(max_length=100)),
                ('activoLibro', models.BooleanField(default=True)),
                ('actualizaLibro', models.DateField(auto_now_add=True)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.autor')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.categoria')),
                ('id_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDePrestamo', models.DateField(auto_now_add=True)),
                ('fechaDeDevolucion', models.DateField()),
                ('id_Usuari0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.usuario')),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.libro')),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.prestamo')),
            ],
        ),
    ]
